import fs from 'fs';

async function checkVibecoding(code, apiKey) {
	const prompt = `Analyze this Sprig game code. Calculate the probability (0 to 100%) that it was generated by an AI (LLM) rather than a beginner programmer. 
You are acting as a forensic code reviewer. We are specifically hunting for "AI Slop" - low-effort, entirely AI-generated games that rely on ChatGPT's standard boilerplate.

CRITICAL AI "giveaways" (increases probability MASSIVELY):
- Numbered Section Comments: ChatGPT almost always outputs Sprig games with numbered headings like "// 1. SET UP THE ART", "// 2. CONFIGURE GAME RULES", "// 3. MOVEMENT LOGIC". If you see this pattern, it is almost certainly AI slop.
- Over-Explaining: Narrating exactly what the syntax does instead of explaining intent.
- Generic Naming: Safe, generic names like \`data\`, \`result\`, \`temp\`, \`item\`.
- Hallucinated APIs: Assuming Sprig has DOM access (e.g. \`document.getElementById\`) or using standard game loop boilerplates.

Crucially, look out for Human "giveaways" (decreases probability significantly):
- Very Specific Assets: Complex, hand-crafted bitmaps or specific tune numbers that were clearly generated using Sprig's built-in visual editor tools. AI struggles to hallucinate perfectly structured Sprig bitmaps.
- Beginner Logic Patterns: Long, inefficient \`if / else if\` chains instead of switches/maps, or slightly clunky procedural code that looks hand-typed by a learner.
- Genuine Game-Specific Naming: Creative, hyper-specific variable names tied directly to the game's theme.
- Expert Human Patterns: Do NOT penalize a game simply for being "too perfect" or well-structured. Expert human developers submit games too! Distinguish between genuine human expertise (clever game loops, thoughtful abstractions, highly customized algorithms) and lazy LLM "polish" (bloated boilerplate, robotic symmetry).

Note: The above points are entirely optional guidelines. You do not need to check them off like a list. Ultimately, you should trust your own intuition and internal logic as an advanced AI to judge whether this code "vibes" like it was written by an LLM or a human learner.

Think critically and identify any other subtle traits. Reply with ONLY a JSON object: {"ai_probability": 85, "reason": "Brief summary of evidence"}.

Code:
${code.substring(0, 5000)}`;

	const models = [
		"~openai/gpt-latest",
		"~google/gemini-pro-latest",
		"~anthropic/claude-sonnet-latest",
		"x-ai/grok-latest",
		"deepseek/deepseek-latest",
		"mistralai/mistral-latest",
		"qwen/qwen-latest"
	];

	try {
		const requests = models.map(model => 
			fetch("https://ai.hackclub.com/proxy/v1/chat/completions", {
				method: "POST",
				headers: {
					"Authorization": `Bearer ${apiKey}`,
					"Content-Type": "application/json"
				},
				body: JSON.stringify({
					model,
					messages: [{ role: "user", content: prompt }],
					response_format: { type: "json_object" }
				})
			})
			.then(res => res.json())
			.then(data => {
                console.log(`[${model}] Response:`, JSON.stringify(data, null, 2));
                return JSON.parse(data.choices[0].message.content);
            })
			.catch(e => {
				console.error(`Model ${model} failed:`, e);
				return null;
			})
		);

		const results = await Promise.all(requests);
		const validResults = results.filter(r => r && typeof r.ai_probability === 'number');

		if (validResults.length === 0) return null;

		const totalProb = validResults.reduce((sum, r) => sum + r.ai_probability, 0);
		const avgProb = Math.round(totalProb / validResults.length);
		
		const rawReasons = [...new Set(validResults.map(r => r.reason).filter(Boolean))].join(" | ");

		let finalReason = rawReasons;
		if (rawReasons.length > 0) {
			const summaryPrompt = `Summarize these AI forensic code review notes into a single concise paragraph. Focus on the main consensus regarding whether the code is AI-generated slop or a genuine human effort.\n\nReviews:\n${rawReasons}`;
			try {
				const summaryReq = await fetch("https://ai.hackclub.com/proxy/v1/chat/completions", {
					method: "POST",
					headers: {
						"Authorization": `Bearer ${apiKey}`,
						"Content-Type": "application/json"
					},
					body: JSON.stringify({
						model: "~openai/gpt-mini-latest",
						messages: [{ role: "user", content: summaryPrompt }]
					})
				});
				const summaryData = await summaryReq.json();
				if (summaryData.choices?.[0]?.message?.content) {
					finalReason = summaryData.choices[0].message.content.trim();
				}
			} catch (e) {
				console.error("Summary failed, using raw reasons", e);
			}
		}

		return { ai_probability: avgProb, reason: finalReason };
	} catch (e) {
		console.error("Vibecoding ensemble check failed:", e);
		return null;
	}
}

const apiKey = process.env.OPENROUTER_API_KEY;
if (!apiKey) {
	console.error("Please set OPENROUTER_API_KEY environment variable");
	process.exit(1);
}
const code = fs.readFileSync("games/MagneticMaze.js", "utf8");
console.log("Testing with games/MagneticMaze.js...");
checkVibecoding(code, apiKey).then(result => {
	if (!result) {
		console.log("Check failed completely.");
		return;
	}
	const prob = result.ai_probability;
	console.log(`\nAI Probability: ${prob}%`);
	console.log(`Reasons: ${result.reason}`);
	if (prob >= 80) {
		console.log("Result: Would be labeled as 'Vibecoded'");
	} else {
		console.log("Result: Would NOT be labeled as 'Vibecoded'");
	}
});
